name: Node.js Package Publishing

on:
  pull_request:
    branches: '**'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Setup Environment
      run: |
        npm install
        export DISPLAY=:99.0
        sudo apt-get install xvfb

    - name: Build Package
      run: xvfb-run ./node_modules/.bin/karma start --single-run
      
    - name: Publish Package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}
      run: npm run semantic-release
